name: '20 - CrePython 20 test of CreLanguageTranslate'
on:
  workflow_dispatch:
  schedule:
#    daily,every 5 hours #m h d/m m d/w 
    - cron:  '20 5 * * *'

jobs:
  versions:
    runs-on: ubuntu-latest
    container:
      image: tamboraorg/crepython:2020.0
      env:
        NEWSAPI_KEY:  ${{ secrets.NEWSAPI_KEY }}
        RAPIDAPI_KEY: ${{ secrets.RAPIDAPI_KEY }}
        GEONAMES_KEY: ${{ secrets.GEONAMES_KEY }}  
      volumes:
        - ${{ github.workspace }}:/cre/python/CreLanguageTranslate

    steps:
      - name: cd
        run: cd /cre/python/CreLanguageTranslate/ 
      - name: pwd
        run: pwd 
      - name: ls
        run:  ls -l 
      - name: run docker in docker
        run: ./test_local.sh 




