name: '20 - CrePython 20 test of CreLanguageTranslate'
on:
  workflow_dispatch:
  schedule:
#    daily,every 5 hours #m h d/m m d/w 
    - cron:  '20 5 * * *'

jobs:
  versions:
    runs-on: ubuntu-latest
    steps:
      - name: pwd
        run: (docker container run --volume ./:/cre/python/CreLanguageTranslate  --workdir /cre/python/CreLanguageTranslate/ credocker/crepython:2020.0 pwd) 
      - name: run docker in docker
        run: (docker container run --volume ./:/cre/python/CreLanguageTranslate  --workdir /cre/python/CreLanguageTranslate/ credocker/crepython:2020.0 ./test_local.sh) 




