name: '20 - CrePython 20 test of CreLanguageTranslate'
on:
  workflow_dispatch:
  schedule:
#    daily,on 5:20  #m h d/m m d/w 
    - cron:  '20 5 * * 0'

# sudo docker container run  --volume ./:/cre/python/CreLanguageTranslate  --workdir /cre/python/CreLanguageTranslate/ credocker/crepython:2020.0 /cre/python/CreLanguageTranslate/test_local.sh

jobs:
  versions:
    runs-on: ubuntu-latest
    container:
      image: credocker/crepython:2020.0
      env:
        NEWSAPI_KEY:  ${{ secrets.NEWSAPI_KEY }}
        RAPIDAPI_KEY: ${{ secrets.RAPIDAPI_KEY }}
        GEONAMES_KEY: ${{ secrets.GEONAMES_KEY }}  
      volumes:
        - ${{ github.workspace }}:/cre/python/CreLanguageTranslate

    steps:
      - name: cd
        run: cd /cre/python/CreLanguageTranslate/ 
      - name: pwd
        run: pwd 
      - name: ls
        run:  ls -l /cre/python/CreLanguageTranslate/
      - name: run docker in docker
        run: /cre/python/CreLanguageTranslate/test_local.sh 




